#!/bin/bash

# name   : winpslist
# url    : http://github.com/4m3rr0r
# author : 4m3rr0r


# Define the exclusion list
exclude_list=("smss.exe" "SearchIndexer.exe" "mscorsvw.exe" "vmtoolsd.exe" "audiodg.exe" "csrss.exe"  "dwm.exe" "explorer.exe" "lsass.exe" "lsm.exe" "SearchFilterHo" "SearchIndexer." "SearchProtocol" "services.exe" "sppsvc.exe" "svchost.exe" "taskhost.exe" "VBoxService.ex" "VBoxTray.exe" "vm3dservice.ex" "wininit.exe" "winlogon.exe" "WmiPrvSE.exe" "spoolsv.exe" "VGAuthService." "wmpnetwk.exe" "dllhost.exe" "System" "DumpIt.exe" "msdtc.exe" )

# Define the highlight words and their corresponding colors
declare -A highlight_words=(

    # Red color 
    ["cmd.exe"]="$(tput setaf 1)"       
    ["TrueCrypt.exe"]="$(tput setaf 1)" 
    ["mspaint.exe"]="$(tput setaf 1)" 
    ["chrome.exe"]="$(tput setaf 1)"
    
    # Green 
    ["KeePass.exe"]="$(tput setaf 2)"
    ["mspaint.exe"]="$(tput setaf 2)"
    ["winrar"]="$(tput setaf 2)"
    
    # Blue color
    ["notepad.exe"]="$(tput setaf 4)" 
    ["conhost.exe"]="$(tput setaf 4)"
    
)

# Function to check if a process should be excluded
should_exclude() {
    local process_name=$1
    for excluded_process in "${exclude_list[@]}"; do
        if [[ "$process_name" == "$excluded_process" ]]; then
            return 0
        fi
    done
    return 1
}

# Function to highlight words in the corresponding colors
highlight_text() {
    local text=$1
    for word in "${!highlight_words[@]}"; do
        local color="${highlight_words[$word]}"
        text=$(echo "$text" | sed "s/\b$word\b/$color&$(tput sgr0)/g")
    done
    echo "$text"
}

# Loop through each line of input received through the standard input
while IFS= read -r line; do
    # Extract the process name from the current line
    process_name=$(echo "$line" | awk '{print $2}')

    # Check if the process should be excluded
    if should_exclude "$process_name"; then
        continue
    fi

    # Highlight words in the line, if any
    line=$(highlight_text "$line")

    # If the process is not excluded and words are highlighted, print the line
    echo "$line"
done
